apiVersion: v1
kind: Secret
metadata:
  name: jarvis-secrets
  namespace: jarvis
type: Opaque
data:
  # Base64 encoded secrets
  # Используйте: echo -n "your_password" | base64
  POSTGRES_PASSWORD: amFydmlzX3NlY3VyZV9wYXNzd29yZA==  # jarvis_secure_password
  SECRET_KEY: amFydmlzLXByb2R1Y3Rpb24tc2VjcmV0LWtleQ==  # jarvis-production-secret-key
  GRAFANA_PASSWORD: YWRtaW4=  # admin