apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: models-pvc
  namespace: jarvis
  labels:
    app.kubernetes.io/name: jarvis
    app.kubernetes.io/instance: jarvis
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: jarvis-ai-assistant
    app.kubernetes.io/managed-by: kustomize
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: knowledge-pvc
  namespace: jarvis
  labels:
    app.kubernetes.io/name: jarvis
    app.kubernetes.io/instance: jarvis
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: jarvis-ai-assistant
    app.kubernetes.io/managed-by: kustomize
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-pvc
  namespace: jarvis
  labels:
    app.kubernetes.io/name: jarvis
    app.kubernetes.io/instance: jarvis
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: jarvis-ai-assistant
    app.kubernetes.io/managed-by: kustomize
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
  namespace: jarvis
  labels:
    app.kubernetes.io/name: jarvis
    app.kubernetes.io/instance: jarvis
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: storage
    app.kubernetes.io/part-of: jarvis-ai-assistant
    app.kubernetes.io/managed-by: kustomize
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
  storageClassName: standard