global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "jarvis_rules.yml"

scrape_configs:
  - job_name: 'jarvis-services'
    static_configs:
      - targets: 
        - 'api-gateway:8000'
        - 'voice-service:8001'
        - 'brain-service:8002'
        - 'task-service:8003'
        - 'web-service:3000'
        - 'code-service:8004'
        - 'learning-service:8005'
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']